### PR TITLE
SC47 datefix

### PR DESCRIPTION
**Pull request by castillar**
Fixes the dates table in `docs/BR.md` to include the 2022 organizationalUnitName deadline.

### CODE REVIEW

**Review by wthayer — COMMENTED** [review]
Should we also add this to the 'relevant dates' table in the EVGLs?

**Comment by castillar** [comment]
Most likely, but I'm having trouble parsing the anchor formatting in use in the EVGL for it. How would it look in that doc?

**Comment by wthayer** [comment]
Added SC47 reference to EVGL relevant dates table

**Comment by castillar** [comment]
Looks good to me!

**Review by DeanJC — COMMENTED** [review]
OK

**Review by DeanJC — APPROVED** [review]

**Review by wthayer — APPROVED** [review]

**Pull request merged**
